name: Palisades Continuous Integration
on: [push]
jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x64]
    runs-on: windows-latest
    env:
      Solution_Path: Palisades.sln
      Palisades_Project_Path: app\Palisades.UI.csproj
      Actions_Allow_Unsecure_Commands: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Nerdbank.GitVersioning to set version variables
        uses: aarnott/nbgv@v0.3
        with:
          setAllVars: true
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Update manifest version
        run: |
          [xml]$manifest = get-content ".\$env:Wap_Project_Directory\Package.appxmanifest"
          $manifest.Package.Identity.Version = "$env:NBGV_SimpleVersion.0"
          $manifest.save(".\$env:Wap_Project_Directory\Package.appxmanifest")
